name: XConn CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-lint:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Start NXT
        run: make run-xconn &

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '6.1.0'

      - name: Run SwiftLint
        uses: cirruslabs/swiftlint-action@v1
        with:
          version: latest
          args: --strict

      - name: Build the package
        run: make build

      - name: Run tests
        run: make test
